version: '3'

services:
    hml:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: AquaGas-Insight
        ports:
            - "3333:3333"
        volumes:
            - ./:/app
            - /app/node_modules
        tty: true
        restart: always