version: '3'

services:
    postgres:
        image: postgres:14-alpine
        ports:
        - "5431:5432"
        volumes:
        - ~/apps/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: "12345"
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "aquaGasDB"

    aqua_gas:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: AquaGas-Insight
        ports:
            - "3333:3333"
        volumes:
            - ./:/app
            - /app/node_modules
        tty: true
        depends_on:
        - postgres
        restart: always